language: erlang
otp_release:
  - 22.0
before_script: cp .travis/rebar.config.script .
script: ./travis/build.sh
deploy:
  provider: script
  script: ./travis/deploy.sh
  skip_cleanup: true
  on:
    tags: true
